# Site settings
title: DtgA Website
description: A welcome and wiki site for DtgA

# GitHub Pages settings
remote_theme: pages-themes/architect@v0.2.0

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude files and folders from the build
exclude:
  - README.md
  - LICENSE

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

# GitHub metadata
github:
  is_project_page: true
